### ISSUE TITLE
Patents and CC0

### ISSUE THREAD

**Issue by dchest** [NTRUOpenSourceProject/NTRUEncrypt#11]
First of all, thank you for releasing patents into the public domain! This is a great and highly appreciated move.

I have a question regarding using CC0 for this, though: CC0's "fallback" license only applies to the copyright and related or neighboring rights ("Copyright and Related Rights"), and the first point in [CC0's Limitations and Disclamers](https://creativecommons.org/publicdomain/zero/1.0/legalcode) is:

> No trademark or patent rights held by Affirmer are waived, abandoned, surrendered, licensed or otherwise affected by this document.

It seems like there's some kind of a conflict between releasing the *patents* into the public domain and the fallback license of CC0. Any clarifications from your lawyers regarding this?

**Comment by wwhyte-si** [comment]
Good question! The patents are intended to also be public domain. To be specific, we will not take any enforcement action against anyone for any use of the indicated patents on or after March 27th, 2017. (And "March 27th, 2017" means "March 27th, 2017 anywhere in the world").

**Comment by dchest** [comment]
Thank you for [clarification](https://github.com/NTRUOpenSourceProject/NTRUEncrypt/commit/76b5bd112368ed39fb1fe10896a8d21189d75231)!
