### ISSUE TITLE
Visual Studio Solution will not build no DLL generated

### ISSUE THREAD

**Issue by kaleb-himes** [NTRUOpenSourceProject/NTRUEncrypt#5]
I am trying to update our .sln project wolfssl-ntru.sln however I am unable to build the ntru .dll following the steps we used to use. These are our instructions that worked when last tested.

...
x) Download ntru-crypto from github
x) Open ntru-crypto\reference-code\C\Encrypt\vs2012\NtruBuild.sln in Visual Studio 2012 or later
x) Build this solution to generate NtruEncrypt_DLL.dll
...

 I get the following failures:

ntru_crypto_ntru_encrypt.obj : error LNK2019: unresolved external symbol _ntru_ring_mult_indices referenced in function _ntru_crypto_ntru_decrypt
ntru_crypto_ntru_poly.obj : error LNK2001: unresolved external symbol _ntru_ring_mult_indices
ntru_crypto_ntru_encrypt.obj : error LNK2019: unresolved external symbol _ntru_ring_mult_coefficients_memreq referenced in function _ntru_crypto_ntru_encrypt_keygen
ntru_crypto_ntru_poly.obj : error LNK2001: unresolved external symbol _ntru_ring_mult_coefficients_memreq
ntru_crypto_ntru_encrypt.obj : error LNK2019: unresolved external symbol _ntru_ring_mult_indices_memreq referenced in function _ntru_crypto_ntru_decrypt
ntru_crypto_ntru_poly.obj : error LNK2001: unresolved external symbol _ntru_ring_mult_indices_memreq
ntru_crypto_ntru_poly.obj : error LNK2019: unresolved external symbol _ntru_ring_mult_coefficients referenced in function _ntru_ring_lift_inv_pow2_product
C:\Users\visualStudio\Desktop\ntru-crypto\reference-code\C\Encrypt\vs2012\Win32\Debug\NtruEncrypt_DLL.dll : fatal error LNK1120: 4 unresolved externals

**Comment by wwhyte-si** [comment]
Thanks – we’ll assign someone to this.



*From:* Kaleb Joseph Himes [mailto:notifications@github.com]
*Sent:* Monday, August 24, 2015 3:24 PM
*To:* NTRUOpenSourceProject/NTRUEncrypt
*Subject:* [NTRUEncrypt] Visual Studio Solution will not build no DLL
generated (#5)



I am trying to update our .sln project wolfssl-ntru.sln however I am unable
to build the ntru .dll following the steps we used to use. These are our
instructions that worked when last tested.

...
x) Download ntru-crypto from github
x) Open ntru-crypto\reference-code\C\Encrypt\vs2012\NtruBuild.sln in Visual
Studio 2012 or later
x) Build this solution to generate NtruEncrypt_DLL.dll
...

I get the following failures:

ntru_crypto_ntru_encrypt.obj : error LNK2019: unresolved external symbol
_ntru_ring_mult_indices referenced in function _ntru_crypto_ntru_decrypt
ntru_crypto_ntru_poly.obj : error LNK2001: unresolved external symbol
_ntru_ring_mult_indices
ntru_crypto_ntru_encrypt.obj : error LNK2019: unresolved external symbol
_ntru_ring_mult_coefficients_memreq referenced in function
_ntru_crypto_ntru_encrypt_keygen
ntru_crypto_ntru_poly.obj : error LNK2001: unresolved external symbol
_ntru_ring_mult_coefficients_memreq
ntru_crypto_ntru_encrypt.obj : error LNK2019: unresolved external symbol
_ntru_ring_mult_indices_memreq referenced in function
_ntru_crypto_ntru_decrypt
ntru_crypto_ntru_poly.obj : error LNK2001: unresolved external symbol
_ntru_ring_mult_indices_memreq
ntru_crypto_ntru_poly.obj : error LNK2019: unresolved external symbol
_ntru_ring_mult_coefficients referenced in function
_ntru_ring_lift_inv_pow2_product
C:\Users\visualStudio\Desktop\ntru-crypto\reference-code\C\Encrypt\vs2012\Win32\Debug\NtruEncrypt_DLL.dll
: fatal error LNK1120: 4 unresolved externals

—
Reply to this email directly or view it on GitHub
<https://github.com/NTRUOpenSourceProject/NTRUEncrypt/issues/5>.

**Comment by kaleb-himes** [comment]
Thank you so much for the quick response wwhyte-si it is most appreciated.

**Comment by jschanck-si** [comment]
I'm going to assume that this has been resolved, but let me know if there are still problems building with VS.
