### ISSUE TITLE
Suggestion: Implement NTRU-KE

### ISSUE THREAD

**Issue by Ipquarx** [NTRUOpenSourceProject/NTRUEncrypt#7]
Here's the paper describing it: https://eprint.iacr.org/2013/718.pdf
As far as I know there are no implementations of it publicly available as of yet, it would be great to see an implementation.

**Comment by wwhyte-si** [comment]
We probably won't implement this exact idea -- this is basically each side encrypts a secret, sends to the other, and puts the result through a KDF, but with the slightly artificial choice that the encrypted secret is also the private key and the KDF involves multiplication. Currently you can get the properties that NTRU-KE gives (i.e. that both sides contribute secret randomness) simply by using standard NTRU in each direction to send two secrets and it's not clear what advantages NTRU-KE would have over that. There may be room for a custom key exchange scheme in the future, but we'd want to make sure it had advantages over the obvious way of doing it.

**Comment by jschanck-si** [comment]
I agree, and if we implement something specifically for key exchange it will be as a separate project, not as part of the NTRUEncrypt reference implementation.

Thanks for the suggestion!
